### ISSUE TITLE
Drawing geometric shapes and images at given coordinates

### ISSUE THREAD

**Issue by coyfi** [Melown/vts-browser-cpp#3]
Greetings,

I was wondering what would be the most straightforward way to draw geometric shapes on the C++ front-end map at certain coordinates? Would using geodata be the correct way to achieve it? 

A simple use case would be to read coordinates and shape identifiers from a file and draw them on the map. A secondary use case would be to draw a given vector or raster image file at the given coordinates, with a title - I believe these are both covered in the tutorials for the Javascript version of VTS Browser, but couldn't quite figure out the C++ equivalent.

Thank you.

**Comment by malytomas** [comment]
Hi Coyfi,
support for geodata is actively being worked on for the c++ browser now. You may follow its progress on the devel branch https://github.com/Melown/vts-browser-cpp/commits/devel .

Current status:
- lines
  - [x] flat or not
  - [x] width: pixels, ratio, meters
  - [x] color
  - [ ] style
- line labels
  - [ ] nothing yet
- points
  - [x] flat or not
  - [x] radius (meters or pixels)
  - [x] color
  - [ ] style
- icons
  - [ ] nothing yet
- labels
  - [x] source
  - [x] fonts
  - [x] size (pixels)
  - [x] color(2)
  - [x] outline
  - [x] origin
  - [x] align
  - [ ] offset
  - [ ] width
  - [ ] stick
  - [x] no-overlap
- polygons
  - [ ] nothing yet
- [x] z-index
- [x] zbuffer-offset
- events, selection and hits
  - [ ] support is not planned
- [x] visibility(-abs | -rel)
- [x] culling
- [x] next-pass
- [x] some undocumented features that are being added to both js and c++ browsers

legend:
  - [x] done
  - [ ] not yet implemented

We strive to make the geodata implementation as compatible as possible, but there will inevitably be differences.

The vts-browser-desktop example app has some capabilities to show / modify geodata and stylesheets.

Note that the devel branch is to be considered unstable.

To answer your question, adding some points with labels is already possible, but adding images (icons) not yet.

Hope this helps.

Cheers,
Tomáš Malý

**Comment by coyfi** [comment]
Thank you for the detailed reply! It is helpful to know what is currently possible to do with the project and what will be in the future - glad that the C++ version is actively developed as well.

It seems we'll be looking at using the Javascript version until the C++ one becomes more mature feature-wise, thus at least for my part this issue could be marked as resolved/closed if preferred.

**Comment by malytomas** [comment]
Hi,
I just wanted to let you know that the things you asked for are now implemented in the c++ browser too.

You may want to give it a try and, please, let us know if you find any problems.

Best,
tm

**Comment by coyfi** [comment]
Thank you for the follow-up, it is good to hear the C++ version is actively developed - will definitely have to try it again the next possible moment.
